/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "new" | "hot" | "sale";
  reviewCount?: number;
  productType?: "objet" | "nourriture" | "autres";
  shippingTime?: "express" | "standard" | "economy" | "global";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/helpers/index.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type=="product"] | order(name asc)
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "hot" | "new" | "sale";
  reviewCount?: number;
  productType?: "autres" | "nourriture" | "objet";
  shippingTime?: "economy" | "express" | "global" | "standard";
}>;

// Source: sanity/helpers/index.ts
// Variable: FOUR_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(name asc)[0...4]{  description,  images,  marque,  reviewCount,  slug,  variants,  }
export type FOUR_PRODUCTS_QUERY_RESULT = Array<{
  description: string | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  marque: Array<string> | null;
  reviewCount: number | null;
  slug: Slug | null;
  variants: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }> | null;
}>;

// Source: sanity/helpers/index.ts
// Variable: SIMILAR_PRODUCTS_QUERY
// Query: *[      _type == "product" &&      _id != $productId &&      (        count((marque)[@ in $marque]) > 0 ||        count((pays)[@ in $pays]) > 0 ||        count((age)[@ in $age]) > 0      )    ][0...4]
export type SIMILAR_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "hot" | "new" | "sale";
  reviewCount?: number;
  productType?: "autres" | "nourriture" | "objet";
  shippingTime?: "economy" | "express" | "global" | "standard";
}>;

// Source: sanity/helpers/index.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" && name match $searchParam] | order(name asc)
export type PRODUCT_SEARCH_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "hot" | "new" | "sale";
  reviewCount?: number;
  productType?: "autres" | "nourriture" | "objet";
  shippingTime?: "economy" | "express" | "global" | "standard";
}>;

// Source: sanity/helpers/index.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "hot" | "new" | "sale";
  reviewCount?: number;
  productType?: "autres" | "nourriture" | "objet";
  shippingTime?: "economy" | "express" | "global" | "standard";
} | null;

// Source: sanity/helpers/index.ts
// Variable: SALE_QUERY
// Query: *[_type == 'sale'] | order(name asc)
export type SALE_QUERY_RESULT = Array<never>;

// Source: sanity/helpers/index.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {      _id,      orderNumber,      stripeCheckoutSessionId,      stripeCustomerId,      clerkUserId,      customerName,      email,      totalPrice,      currency,      status,      orderDate,      shippingAddress {        name,        line1,        line2,        city,        state,        postal_code,        country,        phone      },      shippingMethod,      shippingCost,      amountDiscount,      products[] {        _key,        quantity,        selectedSize,        selectedColor,        selectedShoesSize,        unitPrice,        price,        product->{          _id,          name,          images,          price,          currency,          slug        }      },      invoice {        id,        number,        hosted_invoice_url      }    }
export type MY_ORDERS_QUERY_RESULT = Array<never>;

// Source: sanity/helpers/index.ts
// Variable: PRODUCTS_BY_DAY_QUERY
// Query: *[_type == "product" && Day == $day] | order(name asc)
export type PRODUCTS_BY_DAY_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  origin?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    flavor?: string;
    taille?: string;
    price?: string;
    stock?: number;
    _key: string;
  }>;
  pays?: Array<string>;
  minimum?: number;
  detail?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  marque?: Array<string>;
  age?: Array<string>;
  proteines?: Array<string>;
  regimes?: Array<string>;
  poils?: Array<string>;
  taille_du_chien?: Array<string>;
  types_d_aliments?: Array<string>;
  saveur?: Array<string>;
  benefices_sante?: Array<string>;
  status?: "hot" | "new" | "sale";
  reviewCount?: number;
  productType?: "autres" | "nourriture" | "objet";
  shippingTime?: "economy" | "express" | "global" | "standard";
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="product"] | order(name asc)': PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product"] | order(name asc)[0...4]{\n  description,\n  images,\n  marque,\n  reviewCount,\n  slug,\n  variants,\n  }': FOUR_PRODUCTS_QUERY_RESULT;
    '\n    *[\n      _type == "product" &&\n      _id != $productId &&\n      (\n        count((marque)[@ in $marque]) > 0 ||\n        count((pays)[@ in $pays]) > 0 ||\n        count((age)[@ in $age]) > 0\n      )\n    ][0...4]\n  ': SIMILAR_PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && name match $searchParam] | order(name asc)': PRODUCT_SEARCH_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc) [0]': PRODUCT_BY_ID_QUERY_RESULT;
    "*[_type == 'sale'] | order(name asc)": SALE_QUERY_RESULT;
    '\n    *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {\n      _id,\n      orderNumber,\n      stripeCheckoutSessionId,\n      stripeCustomerId,\n      clerkUserId,\n      customerName,\n      email,\n      totalPrice,\n      currency,\n      status,\n      orderDate,\n      shippingAddress {\n        name,\n        line1,\n        line2,\n        city,\n        state,\n        postal_code,\n        country,\n        phone\n      },\n      shippingMethod,\n      shippingCost,\n      amountDiscount,\n      products[] {\n        _key,\n        quantity,\n        selectedSize,\n        selectedColor,\n        selectedShoesSize,\n        unitPrice,\n        price,\n        product->{\n          _id,\n          name,\n          images,\n          price,\n          currency,\n          slug\n        }\n      },\n      invoice {\n        id,\n        number,\n        hosted_invoice_url\n      }\n    }\n  ': MY_ORDERS_QUERY_RESULT;
    '*[_type == "product" && Day == $day] | order(name asc)': PRODUCTS_BY_DAY_QUERY_RESULT;
  }
}
